import datetime
import os
import yfinance as yf
import pandas as pd
import numpy as np

# ==========================================
# 1. FULL EXPANDED STOCK METADATA DICTIONARY
# ==========================================
STOCK_METADATA = {
    "G13.SI": {
        "name": "Genting Singapore",
        "horizon": "📈 MID-TERM (1–3 YRS)",
        "horizon_grp": "MID",
        "badge_cls": "badge-mid",
        "score": 10,
        "summary": "Value Recovery. Trading near low valuation levels with a strong net-cash balance sheet. RWS 2.0 expansion and resilient tourism volume provide multi-month upside backed by a high dividend yield floor.",
        "catalyst": "RWS 2.0 expansion phases kicking in alongside strong Asian tourism recovery.",
        "fundamentals": "Stable market capitalization with consistent historical dividend payouts.",
        "technicals": "Moving average convergence indicates a potential trend expansion phase.",
        "risks": "General SGX market volatility and sector-specific headwinds.",
        "buy_mult": (0.95, 1.00),
        "target_mult": 1.25,
        "stop_mult": 0.90,
        "intrinsic_val": "S$ 0.72",
        "pb_ratio": "1.20x",
        "fin_years": ["2021", "2022", "2023", "2024", "2025"],
        "fin_rev": ["S$1.06B", "S$1.73B", "S$2.42B", "S$2.55B", "S$2.70B"],
        "fin_net": ["S$183M", "S$345M", "S$611M", "S$650M", "S$710M"],
        "fin_ocf": ["S$320M", "S$580M", "S$890M", "S$940M", "S$1.02B"],
        "fin_fcf": ["S$210M", "S$410M", "S$650M", "S$680M", "S$750M"],
        "fin_div": ["S$0.020", "S$0.030", "S$0.035", "S$0.040", "S$0.045"],
        "asset_cash": ["S$3.1B", "S$3.3B", "S$3.6B", "S$3.8B", "S$4.0B"],
        "asset_st_inv": ["S$120M", "S$150M", "S$180M", "S$200M", "S$220M"],
        "asset_ppe": ["S$4.5B", "S$4.6B", "S$4.8B", "S$5.0B", "S$5.2B"],
        "asset_other": ["S$800M", "S$850M", "S$900M", "S$920M", "S$950M"],
        "asset_total": ["S$8.52B", "S$8.90B", "S$9.48B", "S$9.92B", "S$10.37B"],
        "fin_st_debt": ["S$0M", "S$0M", "S$0M", "S$0M", "S$0M"],
        "fin_lt_debt": ["S$200M", "S$180M", "S$150M", "S$120M", "S$100M"],
        "fin_moat": "Narrow Moat (Gaming License Monopoly) • 8.5/10"
    },
    "OU8.SI": {
        "name": "Centurion Corp",
        "horizon": "📈 MID-TERM (1–3 YRS)",
        "horizon_grp": "MID",
        "badge_cls": "badge-mid",
        "score": 10,
        "summary": "Growth & Supply Shortage. Specialized worker and foreign student accommodation operator benefiting from severe supply shortages across Singapore and the UK.",
        "catalyst": "High occupancy rates and rental rate revisions across PBWA/PBSA assets.",
        "fundamentals": "Strong earnings growth momentum with high dividend coverage.",
        "technicals": "Healthy upward channel with steady accumulation volume.",
        "risks": "Regulatory changes in foreign worker/student quota policies.",
        "buy_mult": (0.95, 0.98),
        "target_mult": 1.24,
        "stop_mult": 0.88,
        "intrinsic_val": "S$ 1.95",
        "pb_ratio": "0.85x",
        "fin_years": ["2021", "2022", "2023", "2024", "2025"],
        "fin_rev": ["S$143M", "S$180M", "S$207M", "S$235M", "S$260M"],
        "fin_net": ["S$52M", "S$71M", "S$153M", "S$175M", "S$195M"],
        "fin_ocf": ["S$75M", "S$98M", "S$128M", "S$145M", "S$165M"],
        "fin_fcf": ["S$45M", "S$68M", "S$92M", "S$110M", "S$125M"],
        "fin_div": ["S$0.010", "S$0.015", "S$0.025", "S$0.035", "S$0.042"],
        "asset_cash": ["S$65M", "S$78M", "S$95M", "S$110M", "S$128M"],
        "asset_st_inv": ["S$10M", "S$12M", "S$15M", "S$18M", "S$20M"],
        "asset_ppe": ["S$1.3B", "S$1.4B", "S$1.6B", "S$1.7B", "S$1.8B"],
        "asset_other": ["S$120M", "S$130M", "S$140M", "S$150M", "S$160M"],
        "asset_total": ["S$1.49B", "S$1.62B", "S$1.85B", "S$1.97B", "S$2.10B"],
        "fin_st_debt": ["S$45M", "S$50M", "S$55M", "S$60M", "S$62M"],
        "fin_lt_debt": ["S$680M", "S$710M", "S$740M", "S$760M", "S$780M"],
        "fin_moat": "Narrow Moat (High Barrier Accommodation) • 7.5/10"
    },
    "BS6.SI": {
        "name": "Yangzijiang Shipbuilding",
        "horizon": "📈 MID-TERM (1–3 YRS)",
        "horizon_grp": "MID",
        "badge_cls": "badge-mid",
        "score": 8,
        "summary": "Record Order Book. Multi-year earnings visibility supported by record high shipbuilding order backlog and strong margin execution.",
        "catalyst": "Delivery of higher-margin clean energy vessel contracts.",
        "fundamentals": "Strong balance sheet with record revenue execution capability.",
        "technicals": "Strong momentum trend trading above key moving averages.",
        "risks": "Steel cost fluctuations and USD/RMB exchange rate volatility.",
        "buy_mult": (0.94, 0.98),
        "target_mult": 1.20,
        "stop_mult": 0.90,
        "intrinsic_val": "S$ 5.30",
        "pb_ratio": "1.65x",
        "fin_years": ["2021", "2022", "2023", "2024", "2025"],
        "fin_rev": ["RMB 16.8B", "RMB 20.7B", "RMB 24.1B", "RMB 27.5B", "RMB 30.2B"],
        "fin_net": ["RMB 3.7B", "RMB 2.8B", "RMB 4.1B", "RMB 4.8B", "RMB 5.5B"],
        "fin_ocf": ["RMB 4.2B", "RMB 3.9B", "RMB 5.8B", "RMB 6.5B", "RMB 7.2B"],
        "fin_fcf": ["RMB 3.1B", "RMB 2.8B", "RMB 4.6B", "RMB 5.2B", "RMB 5.9B"],
        "fin_div": ["S$0.050", "S$0.050", "S$0.065", "S$0.080", "S$0.095"],
        "asset_cash": ["RMB 12B", "RMB 14B", "RMB 17B", "RMB 20B", "RMB 23B"],
        "asset_st_inv": ["RMB 3B", "RMB 3.5B", "RMB 4B", "RMB 4.5B", "RMB 5B"],
        "asset_ppe": ["RMB 8B", "RMB 8.5B", "RMB 9B", "RMB 9.5B", "RMB 10B"],
        "asset_other": ["RMB 5B", "RMB 5.5B", "RMB 6B", "RMB 6.5B", "RMB 7B"],
        "asset_total": ["RMB 28B", "RMB 31.5B", "RMB 36B", "RMB 40.5B", "RMB 45B"],
        "fin_st_debt": ["RMB 1.2B", "RMB 1.0B", "RMB 0.8B", "RMB 0.5B", "RMB 0.3B"],
        "fin_lt_debt": ["RMB 2.5B", "RMB 2.0B", "RMB 1.5B", "RMB 1.0B", "RMB 0.5B"],
        "fin_moat": "Wide Moat (Cost Efficiency & Capacity) • 8.8/10"
    },
    "U11.SI": {
        "name": "UOB Bank",
        "horizon": "📈 MID-TERM (1–3 YRS)",
        "horizon_grp": "MID",
        "badge_cls": "badge-mid",
        "score": 8,
        "summary": "Resilient Yield & Capital Returns. High dividend yield backed by strong regional wealth management expansion and capital optimization.",
        "catalyst": "Integration synergies from Citi ASEAN acquisition and non-interest income growth.",
        "fundamentals": "Solid CET1 ratio supporting sustained dividend payouts and buybacks.",
        "technicals": "Pullback towards support zone creating favorable risk/reward entry.",
